// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//定义用户
type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

//增
type InsertUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertUserReq) Reset()         { *m = InsertUserReq{} }
func (m *InsertUserReq) String() string { return proto.CompactTextString(m) }
func (*InsertUserReq) ProtoMessage()    {}
func (*InsertUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *InsertUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertUserReq.Unmarshal(m, b)
}
func (m *InsertUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertUserReq.Marshal(b, m, deterministic)
}
func (m *InsertUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertUserReq.Merge(m, src)
}
func (m *InsertUserReq) XXX_Size() int {
	return xxx_messageInfo_InsertUserReq.Size(m)
}
func (m *InsertUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_InsertUserReq proto.InternalMessageInfo

func (m *InsertUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InsertUserReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type InsertUserResp struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertUserResp) Reset()         { *m = InsertUserResp{} }
func (m *InsertUserResp) String() string { return proto.CompactTextString(m) }
func (*InsertUserResp) ProtoMessage()    {}
func (*InsertUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *InsertUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertUserResp.Unmarshal(m, b)
}
func (m *InsertUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertUserResp.Marshal(b, m, deterministic)
}
func (m *InsertUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertUserResp.Merge(m, src)
}
func (m *InsertUserResp) XXX_Size() int {
	return xxx_messageInfo_InsertUserResp.Size(m)
}
func (m *InsertUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_InsertUserResp proto.InternalMessageInfo

func (m *InsertUserResp) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertUserResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InsertUserResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertUserResp) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

//删
type DeleteUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserReq) Reset()         { *m = DeleteUserReq{} }
func (m *DeleteUserReq) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReq) ProtoMessage()    {}
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *DeleteUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReq.Unmarshal(m, b)
}
func (m *DeleteUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReq.Marshal(b, m, deterministic)
}
func (m *DeleteUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReq.Merge(m, src)
}
func (m *DeleteUserReq) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReq.Size(m)
}
func (m *DeleteUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReq proto.InternalMessageInfo

func (m *DeleteUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResp) Reset()         { *m = DeleteUserResp{} }
func (m *DeleteUserResp) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResp) ProtoMessage()    {}
func (*DeleteUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *DeleteUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResp.Unmarshal(m, b)
}
func (m *DeleteUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResp.Marshal(b, m, deterministic)
}
func (m *DeleteUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResp.Merge(m, src)
}
func (m *DeleteUserResp) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResp.Size(m)
}
func (m *DeleteUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResp proto.InternalMessageInfo

//改
type ModifyUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserReq) Reset()         { *m = ModifyUserReq{} }
func (m *ModifyUserReq) String() string { return proto.CompactTextString(m) }
func (*ModifyUserReq) ProtoMessage()    {}
func (*ModifyUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *ModifyUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserReq.Unmarshal(m, b)
}
func (m *ModifyUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserReq.Marshal(b, m, deterministic)
}
func (m *ModifyUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserReq.Merge(m, src)
}
func (m *ModifyUserReq) XXX_Size() int {
	return xxx_messageInfo_ModifyUserReq.Size(m)
}
func (m *ModifyUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserReq proto.InternalMessageInfo

func (m *ModifyUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModifyUserReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ModifyUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ModifyUserResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserResp) Reset()         { *m = ModifyUserResp{} }
func (m *ModifyUserResp) String() string { return proto.CompactTextString(m) }
func (*ModifyUserResp) ProtoMessage()    {}
func (*ModifyUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *ModifyUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserResp.Unmarshal(m, b)
}
func (m *ModifyUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserResp.Marshal(b, m, deterministic)
}
func (m *ModifyUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserResp.Merge(m, src)
}
func (m *ModifyUserResp) XXX_Size() int {
	return xxx_messageInfo_ModifyUserResp.Size(m)
}
func (m *ModifyUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserResp proto.InternalMessageInfo

//查
type SelectUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectUserReq) Reset()         { *m = SelectUserReq{} }
func (m *SelectUserReq) String() string { return proto.CompactTextString(m) }
func (*SelectUserReq) ProtoMessage()    {}
func (*SelectUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *SelectUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectUserReq.Unmarshal(m, b)
}
func (m *SelectUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectUserReq.Marshal(b, m, deterministic)
}
func (m *SelectUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectUserReq.Merge(m, src)
}
func (m *SelectUserReq) XXX_Size() int {
	return xxx_messageInfo_SelectUserReq.Size(m)
}
func (m *SelectUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_SelectUserReq proto.InternalMessageInfo

func (m *SelectUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SelectUserResp struct {
	Users                *User    `protobuf:"bytes,1,opt,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectUserResp) Reset()         { *m = SelectUserResp{} }
func (m *SelectUserResp) String() string { return proto.CompactTextString(m) }
func (*SelectUserResp) ProtoMessage()    {}
func (*SelectUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *SelectUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectUserResp.Unmarshal(m, b)
}
func (m *SelectUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectUserResp.Marshal(b, m, deterministic)
}
func (m *SelectUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectUserResp.Merge(m, src)
}
func (m *SelectUserResp) XXX_Size() int {
	return xxx_messageInfo_SelectUserResp.Size(m)
}
func (m *SelectUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_SelectUserResp proto.InternalMessageInfo

func (m *SelectUserResp) GetUsers() *User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*InsertUserReq)(nil), "pb.InsertUserReq")
	proto.RegisterType((*InsertUserResp)(nil), "pb.InsertUserResp")
	proto.RegisterType((*DeleteUserReq)(nil), "pb.DeleteUserReq")
	proto.RegisterType((*DeleteUserResp)(nil), "pb.DeleteUserResp")
	proto.RegisterType((*ModifyUserReq)(nil), "pb.ModifyUserReq")
	proto.RegisterType((*ModifyUserResp)(nil), "pb.ModifyUserResp")
	proto.RegisterType((*SelectUserReq)(nil), "pb.SelectUserReq")
	proto.RegisterType((*SelectUserResp)(nil), "pb.SelectUserResp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x9b, 0xd0, 0xf0, 0xe7, 0xaa, 0x5a, 0xe5, 0xc4, 0x60, 0x31, 0x40, 0xe5, 0xa9, 0x53,
	0x84, 0x8a, 0x78, 0x03, 0x16, 0x06, 0x96, 0x54, 0x2c, 0x6c, 0x4d, 0x7c, 0x88, 0x48, 0x25, 0x31,
	0xbe, 0x80, 0xc4, 0x23, 0xf3, 0x16, 0xc8, 0xb6, 0x50, 0xe2, 0x48, 0x1d, 0xb3, 0xc5, 0x97, 0xfb,
	0xe9, 0xcb, 0xf7, 0x4b, 0x02, 0xf0, 0xc5, 0x64, 0x73, 0x63, 0xdb, 0xae, 0xc5, 0xd4, 0x94, 0xea,
	0x15, 0xe6, 0x2f, 0x4c, 0x16, 0x05, 0xa4, 0xb5, 0x96, 0xc9, 0x3a, 0xd9, 0x64, 0x45, 0x5a, 0x6b,
	0x44, 0x98, 0x37, 0xfb, 0x0f, 0x92, 0xe9, 0x3a, 0xd9, 0x5c, 0x14, 0xfe, 0x1a, 0x25, 0x9c, 0xed,
	0xb5, 0xb6, 0xc4, 0x2c, 0x4f, 0xfc, 0xf8, 0xff, 0x88, 0x57, 0x90, 0x99, 0xf7, 0xb6, 0x21, 0x39,
	0xf7, 0xf3, 0x70, 0x50, 0x15, 0x2c, 0x9f, 0x1a, 0x26, 0xdb, 0xb9, 0x84, 0x82, 0x3e, 0x27, 0x09,
	0xd1, 0x20, 0x86, 0x21, 0x6c, 0x26, 0x49, 0xb9, 0x85, 0xe5, 0x23, 0x1d, 0xa8, 0xa3, 0x23, 0x55,
	0xd4, 0x0a, 0xc4, 0x70, 0x81, 0x8d, 0x6b, 0xff, 0xdc, 0xea, 0xfa, 0xed, 0x67, 0xca, 0xf6, 0x2b,
	0x10, 0xc3, 0x10, 0x36, 0xee, 0x49, 0x77, 0x74, 0xa0, 0xea, 0x98, 0x74, 0x75, 0x07, 0x62, 0xb8,
	0xc0, 0x06, 0x6f, 0x20, 0x73, 0x5f, 0x05, 0xfb, 0xa5, 0xc5, 0xf6, 0x3c, 0x37, 0x65, 0xee, 0x6f,
	0x86, 0xf1, 0xf6, 0x37, 0x81, 0x85, 0x3b, 0xef, 0xc8, 0x7e, 0xd7, 0x15, 0xe1, 0x03, 0x40, 0xaf,
	0x1c, 0x2f, 0xdd, 0x7a, 0xf4, 0x9e, 0xaf, 0x71, 0x3c, 0x62, 0xa3, 0x66, 0x0e, 0xeb, 0x15, 0x05,
	0x2c, 0x72, 0x1a, 0xb0, 0x91, 0x45, 0x8f, 0xf5, 0x15, 0x03, 0x16, 0x79, 0x0d, 0xd8, 0xc8, 0x82,
	0xc7, 0xfa, 0x9a, 0x01, 0x8b, 0xbc, 0x04, 0x2c, 0x36, 0xa1, 0x66, 0xe5, 0xa9, 0xff, 0x35, 0xee,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x0e, 0x8c, 0x31, 0x28, 0x03, 0x00, 0x00,
}
